# Generated by Django 5.1.3 on 2024-12-10 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_dashboard', '0002_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='released_date',
            new_name='release_date',
        ),
    ]
