# Generated by Django 5.1.3 on 2024-12-10 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_dashboard', '0003_rename_released_date_album_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='released_date',
            new_name='release_date',
        ),
    ]
