# Generated by Django 5.1.3 on 2024-12-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_dashboard', '0004_rename_released_date_song_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='spotify_id',
            field=models.TextField(default='Unknown Spotify Id'),
            preserve_default=False,
        ),
    ]
