# Generated by Django 5.1.3 on 2024-12-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_dashboard', '0007_alter_listen_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='listen',
            name='time_listened',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
