# Generated by Django 5.1.3 on 2024-12-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_dashboard', '0008_listen_time_listened'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='release_date',
            field=models.DateField(),
        ),
    ]
